# Generated by Django 6.1.1 on 2026-09-16 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DroughtTolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('tolerancy_days_allowed', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('min_lux', models.IntegerField()),
                ('max_lux', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('min_HR', models.IntegerField()),
                ('max_HR', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=100)),
                ('material', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('volume_litre', models.IntegerField(blank=True, default=None, null=True)),
                ('drying_factor', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('drying_factor', models.FloatField()),
                ('renew_months', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='PlantImages')),
                ('acquisition_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('origin', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('acquisition_price', models.FloatField(blank=True, default=None, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('father', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Plantes.plant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantes.plantstate')),
                ('pot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantes.pot')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('viewed_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('realisation_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantes.action')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantes.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='PlantImages')),
                ('detail', models.JSONField(blank=True, default=None, null=True)),
                ('height', models.FloatField(blank=True, default=None, null=True)),
                ('width', models.FloatField(blank=True, default=None, null=True)),
                ('n_leaves', models.IntegerField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField()),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantes.action')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantes.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vernacular_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('min_temp', models.IntegerField(blank=True, default=None, null=True)),
                ('max_temp', models.IntegerField(blank=True, default=None, null=True)),
                ('drought_tolerance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantes.droughttolerance')),
                ('humidity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantes.humidity')),
                ('max_exposure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_as_max', to='Plantes.exposure')),
                ('min_exposure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species_as_min', to='Plantes.exposure')),
                ('recommended_substrate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantes.substrate')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantes.specie'),
        ),
        migrations.CreateModel(
            name='CareRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.IntegerField()),
                ('month_start', models.IntegerField(default=1)),
                ('month_end', models.IntegerField(default=12)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_rules', to='Plantes.action')),
                ('plant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_rules', to='Plantes.plant')),
                ('specie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_rules', to='Plantes.specie')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('min_temp', models.IntegerField(blank=True, default=None, null=True)),
                ('max_temp', models.IntegerField(blank=True, default=None, null=True)),
                ('drying_factor', models.FloatField(default=1.0)),
                ('has_additional_light', models.BooleanField(default=False)),
                ('has_heater', models.BooleanField(default=False)),
                ('has_moister', models.BooleanField(default=False)),
                ('exposure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantes.exposure')),
                ('humidity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantes.humidity')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantes.spot'),
        ),
        migrations.AddField(
            model_name='plant',
            name='substrate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantes.substrate'),
        ),
    ]
