# Generated by Django 6.1.1 on 2026-09-16 08:40

import Plantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantes', '0002_action_droughttolerance_exposure_humidity_plantstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='gbif_key',
            field=models.BigIntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='specie',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=Plantes.models.specie_image_path),
        ),
        migrations.AddField(
            model_name='specie',
            name='taxon_class',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specie',
            name='taxon_family',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specie',
            name='taxon_genus',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specie',
            name='taxon_order',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specie',
            name='vernacular_name_en',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=Plantes.models.plant_image_path),
        ),
        migrations.AlterField(
            model_name='planthistory',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=Plantes.models.plant_history_image_path),
        ),
        migrations.AlterField(
            model_name='specie',
            name='vernacular_name',
            field=models.CharField(max_length=500),
        ),
    ]
