# Generated by Django 6.1.1 on 2026-09-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantes', '0003_specie_gbif_key_specie_image_specie_taxon_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='cultivar',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
