# Generated by Django 6.1.1 on 2026-09-29 13:49

from datetime import datetime, time

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def backfill_initial_states(apps, schema_editor):
    """
    Le journal devient la source de l'état : chaque plante qui a déjà un état
    reçoit une entrée « Arrivée » qui le porte, sinon il serait effacé au
    premier recalcul. Datée de l'acquisition, à défaut de la création.
    """

    Plant = apps.get_model('Plantes', 'Plant')
    PlantHistory = apps.get_model('Plantes', 'PlantHistory')

    for plant in Plant.objects.filter(state__isnull=False):
        if PlantHistory.objects.filter(plant=plant, state__isnull=False).exists():
            continue

        if plant.acquisition_date:
            date = timezone.make_aware(datetime.combine(plant.acquisition_date, time.min))
        else:
            date = plant.creation_date

        PlantHistory.objects.create(plant=plant, state=plant.state, date=date,
                                    comment='Arrivée dans la collection')


class Migration(migrations.Migration):

    dependencies = [
        ('Plantes', '0005_pot_user_spot_user_alter_plant_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planthistory',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantes.plantstate'),
        ),
        migrations.RunPython(backfill_initial_states, migrations.RunPython.noop),
    ]
